Конструкція try...catch містить два головних блоки: try, а потім catch:

try {

  // код...

} catch (err) {

  // код обробки помилки

}
В першу чергу виконується код в блоці try {...}.
Якщо не виникає помилок, то блок catch (err) ігнорується: виконання досягає кінця блоку try та продовжується поза блоком catch.
Якщо виникає помилка, тоді виконання в try припиняється і виконання коду продовжується з початку блоку catch (err). Змінна err (можна обрати будь-яке ім’я) буде містити об’єкт помилки з додатковою інформацією.